config/routes.rb
Rails.application.routes.draw do
  resources :practitioners
  resources :kit_orders
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'pages#home'
get 'about', to: 'pages#about'
get 'login', to: 'sessions#new'
post 'login', to: 'sessions#create'
delete 'logout', to: 'sessions#destroy'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kit_order.rb
class KitOrder < ActiveRecord::Base

end

app/models/practitioner.rb
class Practitioner < ApplicationRecord
  has_many :kit_orders

  has_secure_password validations: false
  validates :password, presence: true, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= Practitioner.find_by(prac_id: session[:prac_id]) if session[:prac_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in first"
      redirect_to login_path
    end
  end
end

app/controllers/kit_orders_controller.rb
class KitOrdersController < ApplicationController
  def new
    @kitOrder = KitOrder.new
    # debugger
    @prac = Practitioner.find_by(prac_id: session[:prac_id])
    puts "practitioner info:  #{@prac.inspect}"
  end

  def kit_order_params
    params.require(:kit_order).permit(:prac_id, :comment, :location_id)

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

end

app/controllers/practitioners_controller.rb
class PractitionersController < ApplicationController
  before_action :set_practitioner, only: [:show, :edit, :update, :destroy]

  # GET /practitioners
  # GET /practitioners.json
  def index
    @practitioners = Practitioner.all
  end

  # GET /practitioners/1
  # GET /practitioners/1.json
  def show
  end

  # GET /practitioners/new
  def new
    @practitioner = Practitioner.new
  end

  # GET /practitioners/1/edit
  def edit
  end

  # POST /practitioners
  # POST /practitioners.json
  def create
    @practitioner = Practitioner.new(practitioner_params)

    respond_to do |format|
      if @practitioner.save
        format.html { redirect_to @practitioner, notice: 'Practitioner was successfully created.' }
        format.json { render :show, status: :created, location: @practitioner }
      else
        format.html { render :new }
        format.json { render json: @practitioner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /practitioners/1
  # PATCH/PUT /practitioners/1.json
  def update
    respond_to do |format|
      if @practitioner.update(practitioner_params)
        format.html { redirect_to @practitioner, notice: 'Practitioner was successfully updated.' }
        format.json { render :show, status: :ok, location: @practitioner }
      else
        format.html { render :edit }
        format.json { render json: @practitioner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /practitioners/1
  # DELETE /practitioners/1.json
  def destroy
    @practitioner.destroy
    respond_to do |format|
      format.html { redirect_to practitioners_url, notice: 'Practitioner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_practitioner
      @practitioner = Practitioner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def practitioner_params
      params.require(:practitioner).permit(:title)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    prac = Practitioner.find_by(prac_id: params[:session][:prac_id])
    input_pw = params[:session][:password]
    puts "prac information: #{prac.inspect}"
    if prac && check_password(prac.prac_id, input_pw)
      session[:prac_id] = prac.prac_id
      flash[:success] = "You have successfully logged in"
      redirect_to practitioner_path(prac)
    else
      if ! prac
        flash.now[:danger] = "Unrecoginized prac_id: #{params[:session][:prac_id]}"
      end
      flash.now[:danger] = "Failed to login"
      render 'new'
    end
  end

  def destroy
    session[:prac_id] = nil
    flash[:success] = "You have successfully logged out"
    redirect_to login_path
  end

  private

  def check_password(prac_id, password)
    if password == "temp" || password == "password"
      return true
    end
    false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/practitioners_helper.rb
module PractitionersHelper
end

app/views/kit_orders/_form.html.erb
<%= render 'shared/errors', obj: @kitOrder %>

<div class="row">
  <div class="col-xs-12">
    <%= form_for(@kitOrder, :html =>{class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
      <div class="col-sm-2 control-label">
        <%= f.label "Practitioner"  %>
      </div>
      <div class="col-sm-8">
        <%= f.text_field :prac_id, class: "form-control", placeholder: @prac.prac_id, disabled: true, autofocus: true%>
      </div>

      <div class="col-sm-2 control-label">
        <%=  %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-2 control-label">
        <%= f.label :comment %>
      </div>
      <div class="col-sm-8">
        <%= f.text_area :comment, rows: 10, class: "form-control", placeholder: "comment of order" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: 'btn btn-primary btn-lg'%>
      </div>
    </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      [<%= link_to "Cancel request and Back to order list", kit_orders_path %>]
    </div>
  </div>
</div>

app/views/kit_orders/new.html.erb
<h1 align="center">New Order</h1>
<div class="alert alert-success" role="alert">
  <h4 class="alert-heading">Hi <%= @prac.title  %> <%= @prac.first_name %></h4>
  <p>Please select the kit order items below:</p>
</div>
<%= render 'form' %>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      16020 Linden Ave N, Shoreline, WA 98133-5672, USA
      <br>
      Phone: 206.365.1256| Toll Free: 877.318.8728 | Fax: 206.368.8790 | <a href="mailto:cservice@usbiotek.com">cservice@usbiotek.com</a>
    </small>
    <small>
      Copyright &copy; 2018 <a href="https://usbiotek.com">US BioTek</a>
    </small>
    <nav>
      <ul>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%= "#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand" id="logo" href="#">OKOS</a> -->
      <%= link_to "OKOS", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li>
            <%= link_to "Home", root_path %>
        </li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><%= link_to "New Article", root_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to 'Log out', logout_path, method: :delete %></li>
          <li></li>
        <% else %>
          <li><%= link_to 'Log in', login_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Okos</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <style media="screen">
    body {margin: 0px}
  </style>
  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
    <%= debug(session[:prac_id]) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>About</title>
  </head>
  <body>
    <p>About Us</p>
    <%= link_to 'Home', root_path %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>OKOS</h1>
  <%= link_to 'Login', "#", class: "btn-xlg btn btn-primary btn-lg " %>
</div>

app/views/practitioners/_form.html.erb
<%= form_with(model: practitioner, local: true) do |form| %>
  <% if practitioner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(practitioner.errors.count, "error") %> prohibited this practitioner from being saved:</h2>

      <ul>
      <% practitioner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :practitioner_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/practitioners/edit.html.erb
<h1>Editing Practitioner</h1>

<%= render 'form', practitioner: @practitioner %>

<%= link_to 'Show', @practitioner %> |
<%= link_to 'Back', practitioners_path %>

app/views/practitioners/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class='center'>Practitioners</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Clinic Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @practitioners.each do |practitioner| %>
      <tr>
        <td><%= practitioner.title %></td>
        <td><%= practitioner.first_name %></td>
        <td><%= practitioner.last_name %></td>
        <td><%= practitioner.clinic_name %></td>
        <td><%= link_to 'Details', practitioner %></td>
        <!-- <td><%= link_to 'Edit', edit_practitioner_path(practitioner) %></td>
        <td><%= link_to 'Destroy', practitioner, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/practitioners/new.html.erb
<h1>New Practitioner</h1>

<%= render 'form', practitioner: @practitioner %>

<%= link_to 'Back', practitioners_path %>

app/views/practitioners/show.html.erb
<p id="notice"><%= notice %></p>
<div class="col-xs-4 col-xs-offset-4">
  <table class="table">
  <tbody>
    <tr>
      <td><strong>Practitioner ID:</strong></td>
      <td><%= @practitioner.prac_id %></td>
    </tr>
    <tr>
      <td><strong>Title:</strong></td>
      <td><%= @practitioner.title %></td>
    </tr>
    <tr>
      <td><strong>First Name:</strong></td>
      <td><%= @practitioner.first_name %></td>
    </tr>
    <tr>
      <td><strong>Middle Name:</strong></td>
      <td><%= @practitioner.middle_name %></td>
    </tr>
    <tr>
      <td><strong>Last Name:</strong></td>
      <td><%= @practitioner.last_name %></td>
    </tr>
    <tr>
      <td><strong>Clinic Name:</strong></td>
      <td><%= @practitioner.clinic_name %></td>
    </tr>
    <tr>
      <td><strong>Email:</strong></td>
      <td><%= @practitioner.email %></td>
    </tr>
    <tr>
      <td><strong>Delivery Email:</strong></td>
      <td><%= @practitioner.delivery_email %></td>
    </tr>
    <tr>
      <td><strong>Comments:</strong></td>
      <td><%= @practitioner.comment %></td>
    </tr>
  </tbody>

  </table>
  <!-- <%= link_to 'Edit', edit_practitioner_path(@practitioner) %> | -->
  <%= link_to 'Back', practitioners_path %>

</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title">
          <%= pluralize(obj.errors.count, "error") %>
          prohibited this article from being saved:
        </h2>
        <div class="panel-body">
          <ul>
            <% obj.errors.full_messages.each do |msg| %>
            <li>
              <%= msg %>
            </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>